[package]
name = "flagchecker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html\

[dependencies]
reqwest = "*"
tokio = { version = "1", features = ["full"] }
rot13 = "0.1.1"
